language: node_js
node_js:
  - "node"
cache:
  - yarn
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: s3
  skip_cleanup: true
  local_dir: build
  default_text_charset: "utf-8"
  bucket: "www.chriswft-notable.co.uk"
  region: eu-west-1